# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
#logo: 
bio: 'A software engineer, javascript enthusiastic and working at Kiosked. Spends his time travelling the world whenever he has the opportunity. Likes technology, sports and needs to be social'
title: Daniel Bailo
author_pic: '//avatars3.githubusercontent.com/u/1416282?v=3&s=460'
# Content
excerpt_link: Read More

# Miscellaneous
rss:

# Google analytics account
google_analytics: UA-71883268-1