# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
#logo: 
bio: 'A software engineer, javascript enthusiastic and working at Kiosked. Spends his time travelling the world whenever he has the opportunity. Likes technology, sports and needs to be social'
title: Daniel Bailo
# Content
excerpt_link: Read More

# Miscellaneous
rss:
